Add unit testing support (and many other changes)
Groupr-Purdue/Groupr pull request #8
Opened 2017-02-10 09:19 UTC by avaidyam

* Refactored App out into Library for MVC and App retains the Droplet construction and initialization.
* Marked everything as public because that's how to Swift correctly.
* Added simple Auth model (no controller for this one) to begin the micro-OAuth2 impl using JWT.
* Added XCTest unit testing with *nix support - currently no real test cases exist.
* Add @ZachPurdue's CoursesController from #4 with the above changes.

2017-02-10 18:24 UTC, whuang8 requested changes

2017-02-10 18:24 UTC, whuang8 commented on Sources/App/Models/Course.swift
> -    func users() throws -> Siblings<User> {
Why are you deleting users()?

2017-02-10 18:24 UTC, whuang8 commented on Sources/App/Models/User.swift
> -    func courses() throws -> Siblings<Course> {
Same question for this as well.

2017-02-10 18:26 UTC, ZachPurdue commented on Sources/Library/Controllers/UsersController.swift
> +    public func show(request: Request, user: User) throws -> ResponseRepresentable {
Is there a reason everything has to be public?

2017-02-10 18:27 UTC, ZachPurdue commented on Sources/Library/Models/Course.swift
> +        try database.delete("courses")
If reverting, shouldnt it roll back the change, not delete it?

2017-02-10 18:27 UTC, ZachPurdue requested changes
Comments noted

2017-02-10 18:27 UTC, ZachPurdue commented on Sources/Library/Models/User.swift
> +        try database.delete("users")
same revert/delete here

2017-02-10 18:31 UTC, avaidyam commented on Sources/App/Models/Course.swift
> -    func users() throws -> Siblings<User> {
They were moved, not deleted.

2017-02-10 18:31 UTC, avaidyam commented on Sources/App/Models/User.swift
> -    func courses() throws -> Siblings<Course> {
Same answer for this as well.

2017-02-10 18:31 UTC, avaidyam commented on Sources/Library/Controllers/UsersController.swift
> +    public func show(request: Request, user: User) throws -> ResponseRepresentable {
Yes, if you're building a library, unless everything is marked public, these symbols are not accessible outside of the library.

2017-02-10 18:32 UTC, avaidyam commented on Sources/Library/Models/Course.swift
> +        try database.delete("courses")
Correct, this was existing code, I did not modify it past moving it to an extension.

2017-02-10 18:32 UTC, avaidyam commented on Sources/Library/Models/User.swift
> +        try database.delete("users")
Same answer as above.

2017-02-10 18:40 UTC, ZachPurdue commented on Sources/App/Models/Course.swift
> -    func users() throws -> Siblings<User> {
but why is everything being moved around

2017-02-10 18:40 UTC, ZachPurdue commented on Sources/Library/Models/Course.swift
> +        try database.delete("courses")
rip

2017-02-10 18:41 UTC, avaidyam commented on Sources/App/Models/Course.swift
> -    func users() throws -> Siblings<User> {
Because I compartmentalized protocol conformance into its own extension for code readability.

2017-02-10 19:19 UTC, whuang8 commented on Sources/App/Models/User.swift
> -    func courses() throws -> Siblings<Course> {
Ah ok cool. My bad, I didn't see the replacement.

2017-02-10 19:20 UTC, whuang8 approved these changes

2017-02-10 19:20 UTC, avaidyam commented on Sources/App/Models/User.swift
> -    func courses() throws -> Siblings<Course> {
@whuang8 No worries, also, sorry if this messes up the git contributions... didn't mean for that.

2017-02-10 20:57 UTC, ZachPurdue commented
there's no need to revert commits before moving around code and then pushing your own

2017-02-10 20:57 UTC, ZachPurdue approved these changes

2017-02-11 03:12 UTC, avaidyam commented
@ZachPurdue ??? I didn't revert any commits. Your PR wouldn't merge without conflict so I copied your code directly. My apologies.

2017-02-11 03:12 UTC, merged